/**
 * GET /api/cron/weekly-report-email
 *
 * Vercel cron — fires Thursday 13:00 UTC (~8am CDT / 7am CST).
 *
 * Distribution model (matches what the team does manually today):
 *   - Monogastric Weekly (Poultry + Swine combined)  → Poultry & Swine directors
 *   - Ruminant Weekly                                → Ruminant director(s)
 *   - LATAM Weekly                                   → LATAM director(s)
 *   - CEO Weekly (consolidated, all teams)           → CEO only
 *
 * Admin (role='admin', active) is BCC'd on every send for audit/visibility.
 *
 * One Vercel cron invocation produces up to 4 separate Resend sends.
 * Each report's docx is generated by re-calling our existing
 * /api/ai/generate-weekly-report POST route with the matching reportType.
 * That route accepts a CRON_SECRET Bearer token in lieu of a user session
 * so this internal hop works without minting a JWT.
 *
 * Auth: requires `Authorization: Bearer <CRON_SECRET>`.
 */
import { NextRequest } from 'next/server';
import { createClient } from '@supabase/supabase-js';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
export const maxDuration = 60;

interface UserRow { id: string; name: string; email: string; role: string; team: string | null; status: string }
interface ActivityRow { id: string; type: string; subject: string | null; description: string | null; date: string; owner_id: string; account_id: string | null; contact_id: string | null }
interface TaskRow { id: string; subject: string; status: string; due_date: string | null; owner_id: string; related_account_id: string | null }
interface OppRow { id: string; name: string; stage: string; amount: number; close_date: string | null; owner_id: string; account_id: string | null }
interface AccountRow { id: string; name: string }
interface ContactRow { id: string; first_name: string; last_name: string }

type ReportType = 'monogastrics' | 'ruminants' | 'latam' | 'all';

interface ReportPlan {
  reportType: ReportType;
  label: string;            // human-readable, used in Subject + filename
  /**
   * Teams whose Sales Directors should receive this report. `null` means
   * "role only" — used for the CEO Weekly which is purely role-driven.
   */
  recipientTeams: string[] | null;
  recipientRole: 'sales_director' | 'ceo';
  /** Member teams whose data this report represents — used to scope the
   *  body-summary stats so each recipient sees numbers relevant to them. */
  scopeTeams: string[] | 'all';
}

const PLANS: ReportPlan[] = [
  {
    reportType: 'monogastrics',
    label: 'Monogastric Weekly Report (Poultry + Swine)',
    recipientTeams: ['monogastrics', 'swine'],
    recipientRole: 'sales_director',
    scopeTeams: ['monogastrics', 'swine'],
  },
  {
    reportType: 'ruminants',
    label: 'Ruminant Weekly Report',
    recipientTeams: ['ruminants'],
    recipientRole: 'sales_director',
    scopeTeams: ['ruminants'],
  },
  {
    reportType: 'latam',
    label: 'LATAM Weekly Report',
    recipientTeams: ['latam'],
    recipientRole: 'sales_director',
    scopeTeams: ['latam'],
  },
  {
    reportType: 'all',
    label: 'CEO Weekly Report',
    recipientTeams: null,
    recipientRole: 'ceo',
    scopeTeams: 'all',
  },
];

function thisWeekRange(): { from: string; to: string } {
  const today = new Date();
  const dow = today.getDay();
  const daysToMonday = dow === 0 ? 6 : dow - 1;
  const monday = new Date(today.getFullYear(), today.getMonth(), today.getDate() - daysToMonday);
  return { from: monday.toISOString().split('T')[0], to: today.toISOString().split('T')[0] };
}

function buildTeamSummaries(
  allUsers: UserRow[],
  acts: ActivityRow[],
  tasks: TaskRow[],
  opps: OppRow[],
  userById: Map<string, UserRow>,
  acctById: Map<string, string>,
  conById: Map<string, string>,
): Record<string, unknown> {
  // Same shape the client posts to /api/ai/generate-weekly-report. The
  // server side route uses `reportType` to pick which team's section to
  // emit, but expects all teams present in the payload — leaving any
  // out causes silent "no data" rows.
  const teams: { id: string; teamFilter: string; label: string }[] = [
    { id: 'poultry', teamFilter: 'monogastrics', label: 'Poultry' },
    { id: 'swine', teamFilter: 'swine', label: 'Swine' },
    { id: 'ruminants', teamFilter: 'ruminants', label: 'Ruminant' },
    { id: 'latam', teamFilter: 'latam', label: 'LATAM' },
    { id: 'marketing', teamFilter: 'marketing', label: 'Marketing' },
    { id: 'management', teamFilter: 'management', label: 'Management' },
  ];
  const activeUsers = allUsers.filter((u) => u.status === 'active');
  const enrichAct = (a: ActivityRow) => ({
    id: a.id, type: a.type, subject: a.subject || '', description: a.description || '',
    date: a.date, ownerId: a.owner_id, accountId: a.account_id || '', contactId: a.contact_id || '',
    ownerName: userById.get(a.owner_id)?.name || a.owner_id,
    accountName: a.account_id ? acctById.get(a.account_id) || '' : '',
    contactName: a.contact_id ? conById.get(a.contact_id) || '' : '',
  });
  const enrichTask = (t: TaskRow) => ({
    id: t.id, subject: t.subject, status: t.status, dueDate: t.due_date || '',
    ownerId: t.owner_id, relatedAccountId: t.related_account_id || '',
    ownerName: userById.get(t.owner_id)?.name || t.owner_id,
    accountName: t.related_account_id ? acctById.get(t.related_account_id) || '' : '',
  });
  const enrichOpp = (o: OppRow) => ({
    id: o.id, name: o.name, stage: o.stage, amount: Number(o.amount) || 0,
    closeDate: o.close_date || '', ownerId: o.owner_id, accountId: o.account_id || '',
    ownerName: userById.get(o.owner_id)?.name || o.owner_id,
    accountName: o.account_id ? acctById.get(o.account_id) || '' : '',
  });
  const result: Record<string, unknown> = {};
  for (const { id, teamFilter, label } of teams) {
    const memberIds = new Set(activeUsers.filter((u) => {
      if (id === 'management') return u.team === 'management' || (!u.team && ['admin', 'administrative_manager', 'ceo'].includes(u.role));
      return u.team === teamFilter;
    }).map((u) => u.id));
    result[id] = {
      teamName: label,
      activities: acts.filter((a) => memberIds.has(a.owner_id)).map(enrichAct),
      tasks: tasks.filter((t) => memberIds.has(t.owner_id)).map(enrichTask),
      opportunities: opps.filter((o) => memberIds.has(o.owner_id) && o.stage !== 'Closed Lost').map(enrichOpp),
    };
  }
  return result;
}

interface SendResult { plan: string; ok: boolean; recipients: string[]; bcc: string[]; resendId?: string | null; error?: string; skipped?: string }

export async function GET(request: NextRequest) {
  const authHeader = request.headers.get('authorization');
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return Response.json({ error: 'Unauthorized' }, { status: 401 });
  }

  // ── Test mode ─────────────────────────────────────────────────────
  // `?test=1` redirects every report's recipients to admin(s) only and
  // drops the bcc list (since admins would otherwise show up twice).
  // Used for dry-run sanity checks before turning real distribution
  // loose on directors/CEO. Each email still has the real `plan.label`
  // and stats so the admin sees exactly what would have been sent, but
  // the Subject is prefixed `[TEST]` and a yellow banner appears in
  // the body listing the would-be recipients.
  const testMode = request.nextUrl.searchParams.get('test') === '1';

  const sbUrl = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || '';
  const sbKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY || '';
  if (!sbUrl || !sbKey) return Response.json({ error: 'No Supabase config' }, { status: 500 });
  const sb = createClient(sbUrl, sbKey, { auth: { persistSession: false } });

  const { from: fromDate, to: toDate } = thisWeekRange();

  const [usersR, actsR, tasksR, oppsR, acctsR, conR] = await Promise.all([
    sb.from('users').select('id, name, email, role, team, status'),
    sb.from('activities').select('id, type, subject, description, date, owner_id, account_id, contact_id').gte('date', fromDate).lte('date', toDate).is('archived_at', null),
    sb.from('tasks').select('id, subject, status, due_date, owner_id, related_account_id').neq('status', 'Completed'),
    sb.from('opportunities').select('id, name, stage, amount, close_date, owner_id, account_id'),
    sb.from('accounts').select('id, name'),
    sb.from('contacts').select('id, first_name, last_name'),
  ]);
  if (usersR.error || actsR.error || tasksR.error || oppsR.error || acctsR.error || conR.error) {
    return Response.json({ error: 'Supabase fetch failed', detail: {
      users: usersR.error?.message, activities: actsR.error?.message, tasks: tasksR.error?.message,
      opps: oppsR.error?.message, accounts: acctsR.error?.message, contacts: conR.error?.message,
    } }, { status: 500 });
  }
  const allUsers = (usersR.data || []) as UserRow[];
  const acts = (actsR.data || []) as ActivityRow[];
  const tasks = (tasksR.data || []) as TaskRow[];
  const opps = (oppsR.data || []) as OppRow[];
  const accounts = (acctsR.data || []) as AccountRow[];
  const contacts = (conR.data || []) as ContactRow[];

  const userById = new Map(allUsers.map((u) => [u.id, u]));
  const acctById = new Map(accounts.map((a) => [a.id, a.name]));
  const conById = new Map(contacts.map((c) => [c.id, `${c.first_name} ${c.last_name}`]));

  const teamSummaries = buildTeamSummaries(allUsers, acts, tasks, opps, userById, acctById, conById);

  // Admin BCC list — applied to every report send.
  const adminEmails = allUsers
    .filter((u) => u.status === 'active' && u.role === 'admin' && u.email)
    .map((u) => u.email);

  const apiKey = process.env.RESEND_API_KEY;
  const fromOverride = process.env.RESEND_OUTBOUND_FROM_OVERRIDE || 'crm@log.pathway-intermediates.com';
  const base = process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'http://localhost:3000';
  const fmtCurrency = (n: number) => `$${n.toLocaleString('en-US', { maximumFractionDigits: 0 })}`;

  const results: SendResult[] = [];

  for (const plan of PLANS) {
    // ── Pick recipients ───────────────────────────────────────────────
    const realRecipients = allUsers
      .filter((u) => u.status === 'active' && u.role === plan.recipientRole && u.email
        && (plan.recipientTeams === null || (u.team && plan.recipientTeams.includes(u.team))))
      .map((u) => u.email);

    // In test mode the real recipients are noted in the response/body
    // but every email actually goes to admin only.
    const recipients = testMode ? adminEmails : realRecipients;
    const bccForSend = testMode ? [] : adminEmails;

    if (recipients.length === 0) {
      results.push({
        plan: plan.label,
        ok: true,
        recipients: [],
        bcc: bccForSend,
        skipped: testMode ? 'test-mode-no-admins' : 'no-matching-recipients',
      });
      continue;
    }

    // ── Generate docx by re-calling our own report endpoint ──────────
    let docxBuffer: ArrayBuffer | null = null;
    let docxErr: string | null = null;
    try {
      const reportRes = await fetch(`${base}/api/ai/generate-weekly-report`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${process.env.CRON_SECRET}`,
        },
        body: JSON.stringify({ teamSummaries, reportType: plan.reportType }),
      });
      if (!reportRes.ok) {
        const errBody = await reportRes.text().catch(() => '');
        docxErr = `report-${reportRes.status}: ${errBody.slice(0, 300)}`;
      } else {
        docxBuffer = await reportRes.arrayBuffer();
      }
    } catch (err) {
      docxErr = err instanceof Error ? err.message : String(err);
    }
    if (!docxBuffer || docxErr) {
      results.push({ plan: plan.label, ok: false, recipients, bcc: adminEmails, error: docxErr || 'docx-empty' });
      continue;
    }

    // ── Compute per-report summary scoped to this plan's teams ──────
    const teamFilterFn = (u: UserRow) => {
      if (plan.scopeTeams === 'all') return true;
      return u.team !== null && plan.scopeTeams.includes(u.team);
    };
    const scopeMemberIds = new Set(allUsers.filter((u) => u.status === 'active' && teamFilterFn(u)).map((u) => u.id));
    const sActs = acts.filter((a) => scopeMemberIds.has(a.owner_id));
    const sOpps = opps.filter((o) => scopeMemberIds.has(o.owner_id));
    const totalActivities = sActs.length;
    const totalCalls = sActs.filter((a) => a.type === 'Call').length;
    const totalMeetings = sActs.filter((a) => a.type === 'Meeting').length;
    const totalEmails = sActs.filter((a) => a.type === 'Email').length;
    const wonThisWeek = sOpps.filter((o) => o.stage === 'Closed Won' && o.close_date && o.close_date >= fromDate && o.close_date <= toDate);
    const wonAmount = wonThisWeek.reduce((s, o) => s + (Number(o.amount) || 0), 0);
    const openPipeline = sOpps.filter((o) => !['Closed Won', 'Closed Lost'].includes(o.stage)).reduce((s, o) => s + (Number(o.amount) || 0), 0);
    const acctCounts = new Map<string, number>();
    for (const a of sActs) { if (a.account_id) acctCounts.set(a.account_id, (acctCounts.get(a.account_id) || 0) + 1); }
    const topAccounts = [...acctCounts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 5).map(([id, n]) => `${acctById.get(id) || id} (${n})`);

    const filename = `Pathway-${plan.reportType}-Weekly-${toDate}.docx`;
    const summaryHtml = `
      <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;color:#1a1a1a;line-height:1.5;">
        <h2 style="color:#1a4731;margin-bottom:8px;">${plan.label}</h2>
        <p style="color:#666;margin-top:0;font-size:13px;">Week of ${fromDate} → ${toDate}</p>
        <h3 style="color:#1a4731;margin-bottom:6px;font-size:15px;">This Week at a Glance</h3>
        <table style="border-collapse:collapse;font-size:14px;margin-bottom:16px;">
          <tr><td style="padding:4px 16px 4px 0;color:#666;">Activities logged</td><td style="padding:4px 0;"><strong>${totalActivities}</strong> (${totalCalls} calls · ${totalMeetings} meetings · ${totalEmails} emails)</td></tr>
          <tr><td style="padding:4px 16px 4px 0;color:#666;">Deals won</td><td style="padding:4px 0;"><strong>${wonThisWeek.length}</strong> · ${fmtCurrency(wonAmount)}</td></tr>
          <tr><td style="padding:4px 16px 4px 0;color:#666;">Open pipeline</td><td style="padding:4px 0;"><strong>${fmtCurrency(openPipeline)}</strong></td></tr>
        </table>
        ${topAccounts.length > 0 ? `<h3 style="color:#1a4731;margin-bottom:6px;font-size:15px;">Most Active Accounts</h3><ol style="margin-top:0;">${topAccounts.map((t) => `<li style="margin-bottom:2px;">${t}</li>`).join('')}</ol>` : ''}
        <p style="color:#666;font-size:13px;margin-top:24px;">Full breakdown is attached as <code>${filename}</code>.</p>
        <hr style="border:none;border-top:1px solid #eee;margin:24px 0 12px;" />
        <p style="color:#aaa;font-size:12px;">Sent automatically every Thursday morning by Pathway CRM.</p>
      </div>
    `.trim();
    const summaryText = [
      plan.label, `Week of ${fromDate} → ${toDate}`, '',
      'This Week at a Glance',
      `- Activities logged: ${totalActivities} (${totalCalls} calls, ${totalMeetings} meetings, ${totalEmails} emails)`,
      `- Deals won: ${wonThisWeek.length} (${fmtCurrency(wonAmount)})`,
      `- Open pipeline: ${fmtCurrency(openPipeline)}`,
      '',
      topAccounts.length > 0 ? `Most Active Accounts:\n${topAccounts.map((t, i) => `${i + 1}. ${t}`).join('\n')}\n` : '',
      `Full breakdown attached as ${filename}.`,
    ].filter(Boolean).join('\n');

    // ── Send via Resend ─────────────────────────────────────────────
    if (!apiKey || apiKey.includes('placeholder')) {
      results.push({ plan: plan.label, ok: true, recipients, bcc: adminEmails, skipped: 'no-resend-api-key (mock)' });
      continue;
    }
    const base64Docx = Buffer.from(docxBuffer).toString('base64');
    try {
      const res = await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${apiKey}` },
        body: JSON.stringify({
          from: `Pathway CRM <${fromOverride}>`,
          to: recipients,
          bcc: adminEmails.length > 0 ? adminEmails : undefined,
          subject: `${plan.label} — Week of ${fromDate}`,
          html: summaryHtml,
          text: summaryText,
          attachments: [{ filename, content: base64Docx }],
          tags: [
            { name: 'app', value: 'crm' },
            { name: 'type', value: 'weekly-report' },
            { name: 'report', value: plan.reportType },
          ],
        }),
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        results.push({ plan: plan.label, ok: false, recipients, bcc: adminEmails, error: (data as { message?: string }).message || `resend-${res.status}` });
      } else {
        results.push({ plan: plan.label, ok: true, recipients, bcc: adminEmails, resendId: (data as { id?: string }).id || null });
      }
    } catch (err) {
      results.push({ plan: plan.label, ok: false, recipients, bcc: adminEmails, error: err instanceof Error ? err.message : String(err) });
    }
  }

  return Response.json({
    ok: results.every((r) => r.ok),
    week: { from: fromDate, to: toDate },
    adminBcc: adminEmails,
    results,
  });
}
